on:
  pull_request

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout

        - name: Instala o node com a versão
          uses: actions/setup-node
          with:
            node-version: 12

        - name: instalando as dependências
          run: npm i

        - name: executando o lint para verificar se há erros
          run: npx eslint